name: ghcr-smoke
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'agents/_smoke/**'
      - '.github/workflows/ghcr-smoke.yml'

permissions:
  contents: read
  packages: write   # needed to push to ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   # no PAT needed
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: agents/_smoke
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/agent-smoke:latest
