name: agent-readme-check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  readme-enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run README presence/sections check
        run: |
          python scripts/require_agent_readme.py

  # markdownlint:
  #   runs-on: ubuntu-latest
  #   if: always()
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: markdownlint-cli2
  #       uses: DavidAnson/markdownlint-cli2-action@v20
  #       with:
  #         globs: |
  #           **/*.md
